### ISSUE TITLE
How can I require babel's polyfills?

### ISSUE THREAD

**Issue by dgcoffman** [vast/middleman-es6#2]
Getting some `ReferenceError: Can't find variable: Symbol` and `Object doesn't support property or method 'assign'`

Seems like I need babel's polyfills. How can I load them? 

https://babeljs.io/docs/usage/polyfill/

**Comment by vast** [comment]
Hi @dgcoffman, 

The most simple way is to switch to Middleman 4 and do `//= require babel/polyfill`. For more details see: https://github.com/vast/middleman-es6#middleman-4
