### ISSUE TITLE
Using the extension on files without an .es6 extension

### ISSUE THREAD

**Issue by hanno-jonlay** [vast/middleman-es6#3]
Hey @vast 

Very unfamiliar withe ES6 until yesterday! I've been prodded into checking out your extension now that [Zurb Foundation](http://foundation.zurb.com/sites/docs/javascript.html) switched to ES6 for their framework JS.

However, their [JS files](https://github.com/zurb/foundation-sites/tree/master/js) haven't been given the `.es6` extension that your extension requires.

I'm not sure if this is bad practice by Zurb, or if this is a practice that many framework developers are going to follow.

Is it possible to use middleman-es6 without having the `.es6` file extension on scripts? Might you have any suggestions? :smile:

**Comment by vast** [comment]
Sorry, I don't think that it's possible. Consider using external pipeline feature in Middleman 4:https://middlemanapp.com/advanced/external-pipeline/

**Comment by hanno-jonlay** [comment]
Hey, no trouble and thanks for the response. That's a good idea and we'll
look into it as soon as we can upgrade Middleman :D
