### ISSUE TITLE
middleman-es6 incompatible with current Middleman version

### ISSUE THREAD

**Issue by geoffdavis92** [vast/middleman-es6#4]
After installing the gem into my Gemfile, I got an error stating that middleman-es6 is only compatible with a Middleman version above 3.7 and below 4.0; the current stable Middleman is at 4.0.0.

Is there an update in the works to remedy this?

**Comment by vast** [comment]
Loosen Middleman dependency in #6. Give it a try:

```
bundle update middleman-es6
```

**Comment by vast** [comment]
@geoffdavis92, sorry, that won't help. Middleman 4 supports ES6 out of the box without `middleman-es6`.

For more details see: https://github.com/vast/middleman-es6#middleman-4

**Comment by geoffdavis92** [comment]
Thanks!
